(load-file "~/.emacs.d/vendor/TypeScript.el")
(add-to-list 'auto-mode-alist '("\\.ts$" . typescript-mode))
(require 'typescript)
(add-hook 'typescript-mode-hook '(lambda ()
  (local-set-key (kbd "RET") '(lambda ()
    (interactive)
    (reindent-then-newline-and-indent)))
))
